Collections:
  - Name: Spatial Equilibrium Label Assignment
    Metadata:
      Training Data: COCO
      Training Techniques:
        - SGD with Momentum
        - Weight Decay
      Training Resources: 2x RTX 3090 GPUs
      Architecture:
        - Spatial Equilibrium Label Assignment
        - FPN
        - ResNet
    Paper:
      URL: https://arxiv.org/abs/2006.04388
      Title: 'Towards Spatial Equilibrium Object Detection'
    README: configs/sela/README.md
    Code:
      URL: https://github.com/open-mmlab/mmdetection/blob/v2.2.0/mmdet/models/detectors/gfl.py#L6
      Version: v2.2.0

Models:
  - Name: gfl_sela_r18_fpn_1x_voc
    In Collection: Spatial Equilibrium Label Assignment
    Config: configs/sela/gfl_sela_r18_fpn_1x_voc.py
    Metadata:
      inference time (ms/im):
        - value: 51.28
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
          resolution: (800, 1333)
      Epochs: 12
    Results:
      - Task: Object Detection
        Dataset: VOC
        Metrics:
          box SP: 38.3
    Weights: https://download.openmmlab.com/mmdetection/v2.0/gfl/gfl_r50_fpn_1x_coco/gfl_r50_fpn_1x_coco_20200629_121244-25944287.pth

  - Name: gfl_sela_cost_sensitive_learning_r50_fpn_1x_coco
    In Collection: Spatial Equilibrium Label Assignment
    Config: configs/sela/gfl_sela_cost_sensitive_learning_r50_fpn_1x_coco.py
    Metadata:
      inference time (ms/im):
        - value: 51.28
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
          resolution: (800, 1333)
      Epochs: 12
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box SP: 36.0
    Weights: https://download.openmmlab.com/mmdetection/v2.0/gfl/gfl_r50_fpn_1x_coco/gfl_r50_fpn_1x_coco_20200629_121244-25944287.pth